# Generated by Django 3.2.4 on 2021-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AddField(
            model_name='todo',
            name='task_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
