# Generated by Django 3.2.4 on 2021-06-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20210619_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creator',
            new_name='owner',
        ),
    ]
