# Generated by Django 3.2.4 on 2021-06-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_rename_creator_todo_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task_name',
            new_name='text',
        ),
    ]
